version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: resume
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4099:4000
      - 35711:35729
    volumes:
      - ./:/srv/jekyll